services:
  discovery-server:
    image: discovery-server
    build:
      context: discovery-server
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: discovery-server
    container_name: discovery-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "8761:8761"

  paste-service:
    image: paste-service
    build:
      context: paste-service
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: paste-service
    container_name: paste-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/pastebin
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8081:8081"
    depends_on:
      discovery-server:
        condition: service_healthy
      postgres-db:
        condition: service_started
  
  api-gateway:
    image: api-gateway
    build:
      context: api-gateway
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      discovery-server:
        condition: service_healthy

  postgres-db:
    image: postgres:18
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: pastebin
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: