server.port=8081
spring.application.name=paste-service

eureka.instance.hostname=paste-service

eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/

eureka.instance.prefer-ip-address=true