server.port=8080

spring.application.name=api-gateway

eureka.instance.hostname=api-gateway

spring.cloud.gateway.server.webflux.routes[0].id=paste-service-route
spring.cloud.gateway.server.webflux.routes[0].uri=lb://PASTE-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/paste/**

eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true